### ISSUE TITLE
how to use phpmyadmin?

### ISSUE THREAD

**Issue by SolsWebdesign** [supermavster/docker-laravel-8#11]
Thank you for your awesome setup. I got it working with my laravel application. The only thing I am not able to do is get phpMyAdmin working. I can get at it using http://localhost:8081/ but no root or other user & password seems to work. I can get to the CLI but I can find no config.inc.php and cannot create and edit one. I have tried to install nano with various ways ( php /bin/sh -c "sudo yum -y install nano") but cannot get it to install in the CLI.
My application works fine but I can't enter phpmyadmin using those credentials either (and on top of this I don't know what to fill in at "Server" and have tried various things there as well). 
When I use "mysql" as the server name and fill in my database user name and database password I get this error:
mysqli::real_connect(): (HY000/1130): Host 'phpmyadmin.docker-laravel-8_laravel' is not allowed to connect to this MySQL server

So I am doing something wrong :-) please help. How do I install nano or how do I get phpmyadmin working? how to make a config.inc.php and how can I edit it? Many thanks in advance.

**Comment by SolsWebdesign** [comment]
for anyone else running into this: in the end it turned out mysql was not allowing any access at all:
Access denied for 'root'@'localhost' etc etc. I found a similar problem at https://github.com/docker-library/mysql/issues/275 and one person commented: I resolved removing the volumes configuration.
Since I had been able to start a mysql with allowing access outside of de compose yml file, I decided to give it a try:

```
mysql:
    image: mysql:5.7.29
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME} 
      MYSQL_PASSWORD: ${DB_PASSWORD} 
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
  #  volumes:
  #    - ./compose/mysql/my.cnf:/etc/mysql/my.cnf
  #   - dbdata:/var/lib/mysql/
    networks:
      - laravel
```
And that works.
